// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ventiontask.Data.DbContexts;

#nullable disable

namespace Ventiontask.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ventiontask.Domain.Entities.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 7, 18, 4, 22, 28, 734, DateTimeKind.Utc).AddTicks(970),
                            Name = "10-a"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 7, 18, 4, 22, 28, 734, DateTimeKind.Utc).AddTicks(976),
                            Name = "10-b"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 7, 18, 4, 22, 28, 734, DateTimeKind.Utc).AddTicks(978),
                            Name = "10-c"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2023, 7, 18, 4, 22, 28, 734, DateTimeKind.Utc).AddTicks(980),
                            Name = "11-a"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2023, 7, 18, 4, 22, 28, 734, DateTimeKind.Utc).AddTicks(981),
                            Name = "11-a"
                        });
                });

            modelBuilder.Entity("Ventiontask.Domain.Entities.GroupSubject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SubjectId");

                    b.ToTable("GroupSubjects");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 7, 18, 4, 22, 28, 734, DateTimeKind.Utc).AddTicks(1331),
                            GroupId = 1L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 7, 18, 4, 22, 28, 734, DateTimeKind.Utc).AddTicks(1333),
                            GroupId = 2L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 7, 18, 4, 22, 28, 734, DateTimeKind.Utc).AddTicks(1334),
                            GroupId = 2L,
                            SubjectId = 1L
                        });
                });

            modelBuilder.Entity("Ventiontask.Domain.Entities.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 7, 18, 4, 22, 28, 734, DateTimeKind.Utc).AddTicks(1300),
                            Description = "For adults",
                            Name = "History"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 7, 18, 4, 22, 28, 734, DateTimeKind.Utc).AddTicks(1302),
                            Description = "For adults",
                            Name = "Math"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 7, 18, 4, 22, 28, 734, DateTimeKind.Utc).AddTicks(1304),
                            Description = "For adults",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("Ventiontask.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 7, 18, 4, 22, 28, 734, DateTimeKind.Utc).AddTicks(1260),
                            FirstName = "Komron",
                            GroupId = 2L,
                            LastName = "Rakhmonov",
                            Password = "12345",
                            Phone = "+998910082052"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 7, 18, 4, 22, 28, 734, DateTimeKind.Utc).AddTicks(1263),
                            FirstName = "Diyor",
                            GroupId = 1L,
                            LastName = "Rakhmonov",
                            Password = "12345",
                            Phone = "+998910082052"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 7, 18, 4, 22, 28, 734, DateTimeKind.Utc).AddTicks(1268),
                            FirstName = "Sokhib",
                            GroupId = 3L,
                            LastName = "Rakhmonov",
                            Password = "12345",
                            Phone = "+998910082052"
                        });
                });

            modelBuilder.Entity("Ventiontask.Domain.Entities.GroupSubject", b =>
                {
                    b.HasOne("Ventiontask.Domain.Entities.Group", "Group")
                        .WithMany("GroupSubjects")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ventiontask.Domain.Entities.Subject", "Subject")
                        .WithMany("GroupSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Ventiontask.Domain.Entities.User", b =>
                {
                    b.HasOne("Ventiontask.Domain.Entities.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Ventiontask.Domain.Entities.Group", b =>
                {
                    b.Navigation("GroupSubjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Ventiontask.Domain.Entities.Subject", b =>
                {
                    b.Navigation("GroupSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
